name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                script: [build, test, lint]
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: pnpm

            - run: pnpm install --frozen-lockfile

            - name: ${{ matrix.script }}
              run: pnpm ${{ matrix.script }}
